export default  [
    { url: 'http://randomlink..', name: 'Mustafa Lemi', surname: 'ELYAKAN', email: 'mustafa.elyakan@detaysoft.com', viewCount: '124', state:'Aktif',id:1 },
    { url: 'http://randomlink..', name: 'Halil', surname: 'ARSLAN', email: 'halil.arslan@detaysoft.com', viewCount: '221', state:'Kurulum',id:2 },
    { url: 'http://randomlink..', name: 'Osman', surname: 'GÜN', email: 'osman.gun@detaysoft.com', viewCount: '98', state:'Kurulum',id:3 },
    { url: 'http://randomlink..', name: 'Zafer ', surname: 'GÜLER', email: 'zafer.guler@detaysoft.com', viewCount: '75', state:'Aktif',id:4 },
    { url: 'http://randomlink..', name: 'Halit ', surname: 'EMEN', email: 'halit.emen@detaysoft.com', viewCount: '67', state:'Aktif',id:5 },
    { url: 'http://randomlink..', name: 'Yasin', surname: 'GÖRMEZ', email: 'yasin.gormez@detaysoft.com', viewCount: '127', state:'Kurulum',id:6 },
    { url: 'http://randomlink..', name: 'Kenan', surname: 'BAŞDEMİR', email: 'kenan.basdemir@detaysoft.com', viewCount: '56', state:'Aktif',id:7 },
    { url: 'http://randomlink..', name: 'Fatih', surname: 'ÖRNEK', email: 'fatih.ornek@detaysoft.com', viewCount: '137', state:'Aktif',id:8 },
    { url: 'http://randomlink..', name: 'Muhammed Eren', surname: 'DEMİR', email: 'muhammed.demir@detaysoft.com', viewCount: '54', state:'Kurulum',id:9 },
    { url: 'http://randomlink..', name: 'Turhan', surname: 'ÇETİN', email: 'turhan.cetin@detaysoft.com', viewCount: '51', state:'Aktif',id:10 },
    { url: 'http://randomlink..', name: 'Mustafa Lemi', surname: 'ELYAKAN', email: 'mustafa.elyakan@detaysoft.com', viewCount: '124', state:'Aktif',id:11 },
    { url: 'http://randomlink..', name: 'Halil', surname: 'ARSLAN', email: 'halil.arslan@detaysoft.com', viewCount: '221', state:'Kurulum',id:12 },
    { url: 'http://randomlink..', name: 'Osman', surname: 'GÜN', email: 'osman.gun@detaysoft.com', viewCount: '98', state:'Kurulum',id:13 },
    { url: 'http://randomlink..', name: 'Zafer ', surname: 'GÜLER', email: 'zafer.guler@detaysoft.com', viewCount: '75', state:'Aktif',id:14 },
    { url: 'http://randomlink..', name: 'Halit ', surname: 'EMEN', email: 'halit.emen@detaysoft.com', viewCount: '67', state:'Aktif',id:15 },
    { url: 'http://randomlink..', name: 'Yasin', surname: 'GÖRMEZ', email: 'yasin.gormez@detaysoft.com', viewCount: '127', state:'Kurulum',id:16 },
    { url: 'http://randomlink..', name: 'Kenan', surname: 'BAŞDEMİR', email: 'kenan.basdemir@detaysoft.com', viewCount: '56', state:'Aktif',id:17 },
    { url: 'http://randomlink..', name: 'Fatih', surname: 'ÖRNEK', email: 'fatih.ornek@detaysoft.com', viewCount: '137', state:'Aktif',id:18 },
    { url: 'http://randomlink..', name: 'Muhammed Eren', surname: 'DEMİR', email: 'muhammed.demir@detaysoft.com', viewCount: '54', state:'Kurulum',id:19 },
    { url: 'http://randomlink..', name: 'Turhan', surname: 'ÇETİN', email: 'turhan.cetin@detaysoft.com', viewCount: '51', state:'Aktif',id:20 },
    { url: 'http://randomlink..', name: 'Turhan', surname: 'ÇETİN', email: 'turhan.cetin@detaysoft.com', viewCount: '51', state:'Aktif',id:21 },
    { url: 'http://randomlink..', name: 'Mustafa Lemi', surname: 'ELYAKAN', email: 'mustafa.elyakan@detaysoft.com', viewCount: '124', state:'Aktif',id:22 },
    { url: 'http://randomlink..', name: 'Halil', surname: 'ARSLAN', email: 'halil.arslan@detaysoft.com', viewCount: '221', state:'Kurulum',id:23 },
    { url: 'http://randomlink..', name: 'Osman', surname: 'GÜN', email: 'osman.gun@detaysoft.com', viewCount: '98', state:'Kurulum',id:24 },
    { url: 'http://randomlink..', name: 'Zafer ', surname: 'GÜLER', email: 'zafer.guler@detaysoft.com', viewCount: '75', state:'Aktif',id:25 },
    { url: 'http://randomlink..', name: 'Halit ', surname: 'EMEN', email: 'halit.emen@detaysoft.com', viewCount: '67', state:'Aktif',id:26 },
    { url: 'http://randomlink..', name: 'Halit ', surname: 'EMEN', email: 'halit.emen@detaysoft.com', viewCount: '67', state:'Aktif',id:27 },
    { url: 'http://randomlink..', name: 'Mustafa Lemi', surname: 'ELYAKAN', email: 'mustafa.elyakan@detaysoft.com', viewCount: '124', state:'Aktif',id:28 },
    { url: 'http://randomlink..', name: 'Halil', surname: 'ARSLAN', email: 'halil.arslan@detaysoft.com', viewCount: '221', state:'Kurulum',id:29 },
    { url: 'http://randomlink..', name: 'Osman', surname: 'GÜN', email: 'osman.gun@detaysoft.com', viewCount: '98', state:'Kurulum',id:30 },
    { url: 'http://randomlink..', name: 'Zafer ', surname: 'GÜLER', email: 'zafer.guler@detaysoft.com', viewCount: '75', state:'Aktif',id:31 },
    { url: 'http://randomlink..', name: 'Halit ', surname: 'EMEN', email: 'halit.emen@detaysoft.com', viewCount: '67', state:'Aktif',id:32 },
    { url: 'http://randomlink..', name: 'Yasin', surname: 'GÖRMEZ', email: 'yasin.gormez@detaysoft.com', viewCount: '127', state:'Kurulum',id:33 },
    { url: 'http://randomlink..', name: 'Kenan', surname: 'BAŞDEMİR', email: 'kenan.basdemir@detaysoft.com', viewCount: '56', state:'Aktif',id:34 },
    { url: 'http://randomlink..', name: 'Fatih', surname: 'ÖRNEK', email: 'fatih.ornek@detaysoft.com', viewCount: '137', state:'Aktif',id:35 },
    { url: 'http://randomlink..', name: 'Muhammed Eren', surname: 'DEMİR', email: 'muhammed.demir@detaysoft.com', viewCount: '54', state:'Kurulum',id:36 },
    { url: 'http://randomlink..', name: 'Turhan', surname: 'ÇETİN', email: 'turhan.cetin@detaysoft.com', viewCount: '51', state:'Aktif',id:37 },
    { url: 'http://randomlink..', name: 'Mustafa Lemi', surname: 'ELYAKAN', email: 'mustafa.elyakan@detaysoft.com', viewCount: '124', state:'Aktif',id:38 },
    { url: 'http://randomlink..', name: 'Halil', surname: 'ARSLAN', email: 'halil.arslan@detaysoft.com', viewCount: '221', state:'Kurulum',id:39 },
    { url: 'http://randomlink..', name: 'Osman', surname: 'GÜN', email: 'osman.gun@detaysoft.com', viewCount: '98', state:'Kurulum',id:40 },
    { url: 'http://randomlink..', name: 'Zafer ', surname: 'GÜLER', email: 'zafer.guler@detaysoft.com', viewCount: '75', state:'Aktif',id:41 },
    { url: 'http://randomlink..', name: 'Halit ', surname: 'EMEN', email: 'halit.emen@detaysoft.com', viewCount: '67', state:'Aktif',id:42 },
    { url: 'http://randomlink..', name: 'Yasin', surname: 'GÖRMEZ', email: 'yasin.gormez@detaysoft.com', viewCount: '127', state:'Kurulum',id:43 },
    { url: 'http://randomlink..', name: 'Kenan', surname: 'BAŞDEMİR', email: 'kenan.basdemir@detaysoft.com', viewCount: '56', state:'Aktif',id:44 },
    { url: 'http://randomlink..', name: 'Fatih', surname: 'ÖRNEK', email: 'fatih.ornek@detaysoft.com', viewCount: '137', state:'Aktif',id:45 },
    { url: 'http://randomlink..', name: 'Muhammed Eren', surname: 'DEMİR', email: 'muhammed.demir@detaysoft.com', viewCount: '54', state:'Kurulum',id:46 },
    { url: 'http://randomlink..', name: 'Turhan', surname: 'ÇETİN', email: 'turhan.cetin@detaysoft.com', viewCount: '51', state:'Aktif',id:47 },
    { url: 'http://randomlink..', name: 'Turhan', surname: 'ÇETİN', email: 'turhan.cetin@detaysoft.com', viewCount: '51', state:'Aktif',id:48 },
    { url: 'http://randomlink..', name: 'Mustafa Lemi', surname: 'ELYAKAN', email: 'mustafa.elyakan@detaysoft.com', viewCount: '124', state:'Aktif',id:49 },
    { url: 'http://randomlink..', name: 'Halil', surname: 'ARSLAN', email: 'halil.arslan@detaysoft.com', viewCount: '221', state:'Kurulum',id:50 },
    { url: 'http://randomlink..', name: 'Osman', surname: 'GÜN', email: 'osman.gun@detaysoft.com', viewCount: '98', state:'Kurulum',id:51 },
    { url: 'http://randomlink..', name: 'Zafer ', surname: 'GÜLER', email: 'zafer.guler@detaysoft.com', viewCount: '75', state:'Aktif',id:52 },
    { url: 'http://randomlink..', name: 'Halit ', surname: 'EMEN', email: 'halit.emen@detaysoft.com', viewCount: '67', state:'Aktif',id:53 },
    { url: 'http://randomlink..', name: 'Halit ', surname: 'EMEN', email: 'halit.emen@detaysoft.com', viewCount: '67', state:'Aktif',id:54 },
]